install.packages("Rfacebook")
install.packages("Rook")
install.packages("tm")
install.packages("NLP")
install.packages("RColorBrewer")
library("Rfacebook")
library("Rook")
library("tm")
library("wordcloud")

pal2=brewer.pal(8,"Dark2")
token="CAACEdEose0cBANbpq0BDgr2ElUQcBtJa4Hfo4UCug6t1qqOI5pEbyRrOQbIemxP7Lr4xXxCbck5TZAUyB9Qj3Rjy8zY4zRfliAGXVWrGxSXX79omzZCqL51CWaZBeZAY0cxlUlK5a7jEbytl3Pq2TfPh0GhdxWvfWdm4e9lUNO389KCfjg0ZBAQ0su42076hzXR0K7fnmMdcXZAfP4OztBboCLcvLJZAZCIZD"
me = getUsers("me",token=token)
my_friends <- getFriends(token)
page = getPage(page="msbapm",token=token,1000,feed=T)
totallikes = sum(page$likes_count,na.rm=TRUE)
averagelikes = 1104/1000 # 1.1 likesper day
totalcomments = sum(page$comments_count,na.rm=TRUE)
totalshares = sum(page$shares_count,na.rm=TRUE)
tm = c("tm","wordcloud")
# Corpus(DataframeSource(data.frame(as.character(page$message))))
posts = Corpus(DataframeSource(data.frame(as.character(page$message))))
posts = tm_map(posts,removePunctuation)
posts = tm_map(posts,function(x)removeWords(x,stopwords()))
tdm = TermDocumentMatrix(posts)
m = as.matrix(tdm)
v = sort(rowSums(m),decreasing=T)
d= data.frame(word=names(v),freq=v)
wordcloud(d$word,d$freq,min.freq=10)
warnings()
